# Generated by Django 2.0.9 on 2024-01-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='Liquid', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.login')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('purchase', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('Delievery', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('PHARMACY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Epharma.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='purchasehub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('PURCHASE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrating', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('PHARMACY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('file', models.CharField(default=1, max_length=200)),
                ('size', models.CharField(default=1, max_length=200)),
                ('price', models.CharField(default=1, max_length=200)),
                ('MEDICINE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.Medicine')),
                ('PHARMACY', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('Housename', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.login')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.user'),
        ),
        migrations.AddField(
            model_name='purchasehub',
            name='STOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.stock'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.user'),
        ),
        migrations.AddField(
            model_name='cart',
            name='PHARMACY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.pharmacy'),
        ),
        migrations.AddField(
            model_name='cart',
            name='STOCK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.stock'),
        ),
        migrations.AddField(
            model_name='cart',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Epharma.user'),
        ),
    ]
