# Generated by Django 3.2.23 on 2024-03-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epharma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='PHARMACY',
        ),
    ]
