# Generated by Django 3.2.23 on 2024-03-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Epharma', '0004_auto_20240306_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('cdate', models.CharField(max_length=200)),
                ('reply', models.CharField(default='pending', max_length=200)),
                ('rdate', models.CharField(default='pending', max_length=200)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Epharma.user')),
            ],
        ),
    ]
