# Generated by Django 3.2.23 on 2024-03-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epharma', '0006_alter_address_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Delievery',
        ),
    ]
